name: datascience
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  # - dask
  # - pyarrow
  # - scikit-learn
  - jupyter
  - jupyterlab
  # - descartes
  - pyjanitor
  # - rtree
  # - fiona
  # - shapely
  - geopandas
  - pip
  - pip:
      - matplotlib
      - seaborn
      # - altair
      - numpy
      - seaborn
      - pandas
      # - us
      # - census
      - requests
