name: datascience
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - scikit-learn
  - jupyter
  - jupyterlab
  - rtree
  - fiona
  - shapely
  - geopandas
  - pip
  - pip:
      - matplotlib
      - seaborn
      - altair
      - numpy
      - seaborn
      - pandas
      - us
      - census
      - requests
